apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- hpa.yaml
- canary.yaml
- service.yaml
- loadtester.yaml

components:
- ../common-gateway

configMapGenerator:
- envs:
  - "version.env"
  name: environment-variables

images:
- name: peerapach/mirror-http-server
  newTag: 1.1.2
- name: peerapach/mirror-http-server
  newTag: v1
