apiVersion: v1
kind: Service
metadata:
  name: api-flagger
  labels:
    app: api-flagger
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: api-flagger
