apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: api-argo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-argo
  template:
    metadata:
      labels:
        app: api-argo
    spec:
      containers:
      - name: api-argo
        image: eexit/mirror-http-server:1.1.0
        ports:
        - containerPort: 80
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
    canary: #Indicates that the rollout should use the Canary strategy
      maxSurge: "25%"
      maxUnavailable: 0
      canaryService: api-argo-canary
      stableService: api-argo
      analysis:
        templates:
        - templateName: success-rate
          clusterScope: true
        - templateName: latency
          clusterScope: true
        args:
        - name: namespace
          value: default
        - name: service-name
          value: api-argo-canary
        startingStep: 1
      steps:
      - setCanaryScale:
          matchTrafficWeight: true
      - setWeight: 10
      - pause:
          duration: 2m
      - setWeight: 15
      - pause: { duration: 120 }
      - setWeight: 25
      - pause: { duration: 120s }
      - setWeight: 50
      - pause: {duration: 3m}
      trafficRouting:
        istio:
          # Either virtualService or virtualServices can be configured.
          virtualService: 
            name: api-argo-vsvc  # required
            routes:
            - primary # optional if there is a single route in VirtualService, required otherwise
