apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api-argo
spec:
  maxReplicas: 6
  minReplicas: 2
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: api-argo
  targetCPUUtilizationPercentage: 80