apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- hpa.yaml
- service.yaml
- vsvc.yaml

components:
- ../common-gateway

images:
- name: eexit/mirror-http-server
  newTag: 1.1.1
