apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
- https://argoproj.github.io/argo-rollouts/features/kustomize/rollout-transform.yaml

resources:
- deployment.yaml
- hpa.yaml
- service.yaml
- vsvc.yaml

configMapGenerator:
- envs:
  - version.env
  name: environment-variables

components:
- ../common-gateway

images:
- name: peerapach/mirror-http-server
  newTag: 1.1.5
