apiVersion: v1
kind: Service
metadata:
  name: api-argo
  labels:
    app: api-argo
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: api-argo
---
apiVersion: v1
kind: Service
metadata:
  name: api-argo-canary
  labels:
    app: api-argo
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: api-argo
