apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
 name: api-argo-vsvc
spec:
 gateways:
 - api-gateway
 hosts:
 - "*"
 http:
 - name: primary        # referenced in canary.trafficRouting.istio.virtualService.routes
   route:
   - destination:
       host: api-argo # referenced in canary.stableService
     weight: 100
   - destination:
       host: api-argo-canary # referenced in canary.canaryService
     weight: 0
