apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
  - name: service-name
  - name: namespace
  metrics:
  - name: success-rate
    interval: 2m
    successCondition: result[0] >= 90
    failureLimit: 3
    provider:
      prometheus:
        address: http://prometheus.istio-system:9090
        query: |
          (sum (
                rate(
                  istio_requests_total{
                    destination_workload_namespace="{{args.namespace}}",
                    destination_service_name=~"{{args.service-name}}",
                    response_code!~"5.*"
                  }[2m]
                )
              )
              /
              sum ( 
                rate(
                  istio_requests_total{
                    destination_workload_namespace="{{args.namespace}}",
                    destination_service_name=~"{{args.service-name}}",
                  }[2m]
                ) 
              ) )* 100
