---
apiVersion: argoproj.io/v1alpha1
kind: ClusterAnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
  - name: service-name
  - name: namespace
  metrics:
  - name: success-rate
    interval: 2m
    successCondition: result[0] >= 90
    failureLimit: 3
    provider:
      prometheus:
        address: http://prometheus.istio-system:9090
        query: |
          (sum (
                rate(
                  istio_requests_total{
                    destination_workload_namespace="{{args.namespace}}",
                    destination_service_name=~"{{args.service-name}}",
                    response_code!~"5.*"
                  }[2m]
                )
              )
              /
              sum ( 
                rate(
                  istio_requests_total{
                    destination_workload_namespace="{{args.namespace}}",
                    destination_service_name=~"{{args.service-name}}",
                  }[2m]
                ) 
              ) )* 100
---
apiVersion: argoproj.io/v1alpha1
kind: ClusterAnalysisTemplate
metadata:
  name: not-found-percentage
spec:
  args:
  - name: service-name
  - name: namespace
  metrics:
  - name: not-found-percentage
    interval: 2m
    successCondition: result[0] >= 10
    failureLimit: 3
    provider:
      prometheus:
        address: http://prometheus.istio-system:9090
        query: |
          100 - sum(
            rate(
                istio_requests_total{
                  reporter="destination",
                  destination_workload_namespace="{{ args.namespace }}",
                  destination_service_name="{{args.service-name}}",
                  response_code!="404"
                }[2m]
            )
          )
          /
          sum(
              rate(
                  istio_requests_total{
                    reporter="destination",
                    destination_workload_namespace="{{ args.namespace }}",
                    destination_service_name="{{args.service-name}}"
                  }[2m]
              )
          ) * 100
---
apiVersion: argoproj.io/v1alpha1
kind: ClusterAnalysisTemplate
metadata:
  name: latency
spec:
  args:
  - name: service-name
  - name: namespace
  metrics:
  - name: latency
    interval: 2m
    successCondition: result[0] <= 200
    failureLimit: 3
    provider:
      prometheus:
        address: http://prometheus.istio-system:9090
        query: |
          histogram_quantile(
            0.99,
            sum(
                rate(
                    istio_request_duration_milliseconds_bucket{
                        destination_workload_namespace="{{ args.namespace }}",
                        destination_service_name=~"{{ args.service-name }}",
                    }[2m]
                )
            ) by (le)
          )